AWSTemplateFormatVersion: "2010-09-09"
Description: "API Gateway stage"

Parameters:
  ServiceName:
    Type: String
    Description: Service name
    Default: mache-viewer
  Phase:
    Type: String
    Description: Phase
    AllowedValues:
      - ci
      - dev
      - prd
  StageName:
    Type: String
    Description: Phase
    AllowedValues:
      - live
      - test
  APIGatewayId:
    Type: String
    Description: API Gateway
  APIGatewayDeploymentId:
    Type: String
    Description: API Gateway deployment
  APIFunctionAlias:
    Type: String
    Description: Alias name

Resources:
  APIGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref StageName
      RestApiId: !Ref APIGatewayId
      DeploymentId: !Ref APIGatewayDeploymentId
      Variables:
        APIFunctionAlias: !Ref APIFunctionAlias
      Tags:
        - Key: Service
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref Phase

Outputs:
  APIGatewayStageId:
    Description: API Gateway stage
    Value: !Ref APIGatewayStage
