AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda version"

Parameters:
  APIFunction:
    Type: String
    Description: API function V1

Resources:
  APIFunctionVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref APIFunction

Outputs:
  APIFunctionVersion:
    Description: API function version number
    Value: !GetAtt APIFunctionVersion.Version
