AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda alias"

Parameters:
  AliasName:
    Type: String
    Description: Alias name
  APIFunction:
    Type: String
    Description: API function
  APIFunctionVersion:
    Type: String
    Description: API function version number

Resources:
  APIFunctionAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref APIFunction
      FunctionVersion: !Ref APIFunctionVersion
      Name: !Ref AliasName
      Description: !Sub ${AliasName} alias
      RoutingConfig:
        AdditionalVersionWeights:
          - FunctionVersion: !Ref APIFunctionVersion
            FunctionWeight: 1
