name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  build:
    needs: [ check ]
    uses: ./.github/workflows/build.yml
    secrets: inherit
