name: Main Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  upload:
    needs:
      - check
      - build
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      build_version: ${{ needs.build.outputs.build_version }}

  deploy:
    needs:
      - build
      - upload
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      phase: dev
      build_version: ${{ needs.build.outputs.build_version }}

  tag:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    steps:
      - uses: actions/checkout@v4
      - name: Tag name
        id: tag-name
        run: |
          echo "tag_name=v${{ needs.build.outputs.build_version }}" >> $GITHUB_OUTPUT
      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag-name.outputs.tag_name }}
          generate_release_notes: true
