name: Release Pipeline

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build-version: ${{ steps.build-version.outputs.version }}
    steps:
      - name: Get build version
        id: build-version
        run: |
          BUILD_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed -e 's/^v//')
          echo "version=${BUILD_VERSION}" >> $GITHUB_OUTPUT

  deploy:
    needs:
      - setup
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      phase: prd
      build_version: ${{ needs.setup.outputs.build-version }}
