name: Build

on:
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
    steps:
      - run: echo "build_version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

  build-backend:
    needs:
      - version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - name: Install backend dependencies
        run: npm ci
      - name: Build backend
        run: npm run build
      - name: Zip backend
        run: zip -rj function.zip dist/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Upload function.zip to S3
        run: |
          aws s3 cp function.zip \
            s3://${{env.ServiceName}}-cmn-mdl/build/${{needs.version.outputs.build_version}}/backend/function.zip
