name: Build

on:
  workflow_call:
    outputs:
      build_version:
        description: 'Build version (yyyyMMddHHmmss)'
        value: ${{ jobs.version.outputs.build_version }}

env:
  ServiceName: mache-viewer

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
    steps:
      - id: version
        run: echo "build_version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  build-backend:
    needs:
      - version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Install backend dependencies
        run: npm ci
      - name: Build backend
        run: npm run build
      - name: Zip backend
        run: zip -rj function.zip dist/*
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ServiceName }}-backend-${{ needs.version.outputs.build_version }}
          path: backend/function.zip
          retention-days: 1

  build-frontend:
    needs:
      - version
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ServiceName }}-frontend-${{ needs.version.outputs.build_version }}
          path: frontend/dist
          retention-days: 1
