name: Check

on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          shopt -s globstar
          cfn-lint --version
          cfn-lint -t infra/cfn/**/*.yaml
