name: Check infra

on:
  workflow_call:

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          shopt -s globstar
          cfn-lint --version
          cfn-lint -t infra/cfn/**/*.yaml

  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx @stoplight/spectral-cli lint swagger-v1.yaml
        working-directory: infra
