name: Check

on:
  workflow_dispatch:
    parameters:
      phase:
        description: Phase
        required: true
        default: ci
      build_version:
        description: Build version (yyyyMMddHHmmss)
        required: true
  workflow_call:
    parameters:
      phase:
        description: Phase
        required: true
        default: ci
      build_version:
        description: Build version (yyyyMMddHHmmss)
        required: true

env:
  ServiceName: mache-viewer

jobs:
  update-common-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Deploy cloudformation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{env.ServiceName}}-common-stack
          template: infra/cfn/common-stack.yaml
          no-fail-on-empty-changeset: true
          parameter-overrides: |
            ServiceName=${{env.ServiceName}}

  update-stateful-stack:
    needs:
      - update-common-stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Upload OpenAPI specification to S3
        run: aws s3 cp infra/swagger-v1.yaml s3://${{env.ServiceName}}-cmn-mdl/build/${{inputs.build_version}}/infra/swagger-v1.yaml
      - name: Deploy cloudformation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{env.ServiceName}}-${{inputs.phase}}-stateful-stack
          template: infra/cfn/stateful-stack.yaml
          no-fail-on-empty-changeset: true
          parameter-overrides: |
              ServiceName=${{env.ServiceName}}
              Phase=${{inputs.phase}}
              S3KeyOpenApi=build/${{inputs.build_version}}/infra/swagger-v1.yaml
              S3KeyCode=build/${{inputs.build_version}}/backend/function.zip
