name: Build

on:
  workflow_call:
    inputs:
      build_version:
        type: string
        description: Build version (yyyyMMddHHmmss)
        required: true

env:
  ServiceName: mache-viewer

jobs:

  update-common-stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Deploy cloudformation stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{env.ServiceName}}-common
          template: infra/cfn/common-stack.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: |
            ServiceName=${{env.ServiceName}}

  build-backend:
    needs:
      - update-common-stack
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ServiceName }}-backend-${{ inputs.build_version }}
          path: .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Upload function.zip to S3
        run: |
          aws s3 cp function.zip \
            s3://${{env.ServiceName}}-cmn-mdl/build/${{needs.version.outputs.build_version}}/backend/function.zip

  build-frontend:
    needs:
      - update-common-stack
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.ServiceName }}-frontend-${{ inputs.build_version }}
          path: .
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_DEPLOY_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Upload build to S3
        run: |
          aws s3 sync dist/ \
            s3://${{env.ServiceName}}-cmn-mdl/build/${{needs.version.outputs.build_version}}/frontend/
